### ISSUE TITLE
Oportunidad de mejorar en TicketEntity

### ISSUE THREAD

**Issue by enelramon** [aaron-developer25/Ticketing#3]
https://github.com/aaron-developer25/Ticketing/blob/bef78ef6ddd3300d0a7075528395d62ae6decd31/app/src/main/java/com/aarondeveloper/ticketing/data/local/entities/TicketEntity.kt#L8

### 1. **Evitar `var` y preferir `val`**
- **Inmutabilidad y seguridad**: Usar `val` promueve la inmutabilidad, lo que reduce errores y mejora la seguridad del código en entornos concurrentes.
- **Referencia**: La [documentación oficial de Kotlin](https://kotlinlang.org/docs/coding-conventions.html#properties) recomienda preferir `val` para escribir código más claro y seguro.

### 2. **Uso de camelCase en nombres de campos**
- **Consistencia y legibilidad**: Kotlin sigue la convención de **camelCase** para propiedades, lo que asegura un código más consistente y fácil de leer.
- **Referencia**: La [guía de estilo de Kotlin](https://kotlinlang.org/docs/coding-conventions.html#property-names) establece el uso de **camelCase** para propiedades, lo que facilita la interoperabilidad y compatibilidad con otras herramientas.

### 3. **Nombres de llaves foráneas y nulabilidad**
- La llave foránea PrioridadId, **no debe ser nullable** ya que una prioridad siempre debe estar presente en un ticket

**Comment by aaronherg** [comment]
Estimado @enelramon,

Agradezco su observación. He solucionado lo indicado en el commit 8d42ad8332d69c301156e1080d42e2abd44ca908

Agradezco su sugerencia y quedo a su disposición para cualquier otra consulta.

Saludos cordiales,
Aaron Hernandez
