### ISSUE TITLE
Oportunidades de mejora TicketDao

### ISSUE THREAD

**Issue by enelramon** [aaron-developer25/Ticketing#4]
https://github.com/aaron-developer25/Ticketing/blob/bef78ef6ddd3300d0a7075528395d62ae6decd31/app/src/main/java/com/aarondeveloper/ticketing/data/local/dao/TicketDao.kt#L11

1. **Uso de `@Upsert` sin paréntesis**: 
   - La anotación `@Upsert` no requiere paréntesis si no estás pasando parámetros adicionales. Los paréntesis pueden ser omitidos cuando no se especifican atributos.
   - **Cambio**: `@Upsert()` a `@Upsert`.

2. **Corregir el nombre del parámetro en `delete`**: 
   - El nombre del parámetro `da` en el método `delete` no es descriptivo. Debe seguir las mismas convenciones de nomenclatura que el resto de los métodos.
   - **Cambio**: Renombrar `da` a `ticket` para mantener consistencia y claridad en los nombres de los parámetros.

3. **Espacios y estilo en la consulta SQL**:
   - En el método `find`, la consulta SQL debería tener espacios alrededor de los operadores para mejorar la legibilidad.
   - **Cambio**: `WHERE TicketId=:id` a `WHERE TicketId = :id`.

**Comment by aaronherg** [comment]
Estimado @enelramon,

Agradezco su observación. He solucionado lo indicado en el commit 245e9b6addb4eb3b270171898df8ec639e899cbe

Agradezco su sugerencia y quedo a su disposición para cualquier otra consulta.

Saludos cordiales,
Aaron Hernandez
