### ISSUE TITLE
Falta el Directorio di 

### ISSUE THREAD

**Issue by enelramon** [aaron-developer25/Ticketing#5]
https://github.com/aaron-developer25/Ticketing/blob/bef78ef6ddd3300d0a7075528395d62ae6decd31/app/src/main/java/com/aarondeveloper/ticketing/data/local/AppModule.kt#L15
app/
├── src/
│   ├── main/
│   │   ├── kotlin/                # Código fuente Kotlin
│   │   │   └── com/
│   │   │       └── aarondeveloper/
│   │   │           └── ticketing/ # Paquete base de la app
│   │   │               ├── data/  # Clases relacionadas con datos (repositorios, fuentes de datos)
│   │   │               │   ├── local/
│   │   │               │   ├── remote/
│   │   │               │   └── model/
│   │   │               ├── di/    # Clases relacionadas con la inyección de dependencias (Dagger, Hilt)

**Comment by aaronherg** [comment]
Estimado @enelramon,

Agradezco su observación. He solucionado lo indicado en el commit d833a052a0df9b02df5f6ffee456b98953b00747

Agradezco su sugerencia y quedo a su disposición para cualquier otra consulta.

Saludos cordiales,
Aaron Hernandez

**Comment by enelramon** [comment]
Te puse el árbol de carpetas para que notaras que di va al mismo nivel que data

**Comment by aaronherg** [comment]
Ohh! Le juro que pense que lo habia puesto en esa posicion. Descuide lo hare.
